# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: MyNameIs
  value: 'Fred The Owner'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: |
      echo ${{ variables.MyNameIs}} # outputs initialValue
      echo $(one)
- task: BatchScript@1
  inputs:
    filename: 'c:\junk\xxx.bat'
    arguments: 'arg1 arg2'